sudo: false
cache:
  directories:
  - $HOME/.gradle
language: groovy
jdk:
- openjdk8
install: true
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Jeff Scott Brown"
  - GIT_EMAIL="brownj@objectcomputing.com"
